### PR TITLE
Feature/refine form styles

### LINKED ISSUE #69: Enhance form styles
- [x] I would align fields to the right -> See https://github.com/EyeSeeTea/vaccination-app/pull/64

Now
- [x] Split tables for wide rows (NRC-like) 
- [x] Create two sections -> “Doses administered” and “Quality and safety indicators”
- [x] Remove light blue border from cell

Later
- [ ] Any explanation on top of the form

### PR DESCRIPTION
**Pull request by tokland**
### :pushpin: References

* **Issue:** Closes #69 

### :memo: Implementation

- I've checked the split code for NRC, and there we have some restrictions because initially the split had  to be done from the automatic form, so we only had the HTML to work. Here, we have custom form, so I've used a different approach, do the hard work already in the custom form generation: 
  - Render a table with all categories.
  - Render another second bunch of tables with the first category (age range) split, one table per age range.
  - The code run on the client calculates the width of those tables in the group and leaves only visible the one that fits. 
  - I could write a generic code that creates more split tables, but it seems overkill on our case (max: 2 gender * 3 displacement = 6 cocs in row). But it can be done if necessary.

### :art: Screenshots

Screenshot from 2019-04-12 17-30-21

### CODE REVIEW

**Comment by tokland** [comment]
Yep, you are right. Refactored so we can get the width of table elements (visible or not). Also, added yarn localize to the prebuild task, it's required by the tests.

**Comment by adrianq** [comment]
Thanks for this. It looks very nice now! Something very minor, can you increase a bit the column width?
image

and can you increase the margin between the two columns 20px or so?

**Comment by tokland** [comment]
1) We can reduce the padding (10px) to 5px for example, now it fits: Screenshot from 2019-04-14 23-12-41

2) Which two columns? the data values td? Now it's 4px (2*2px of padding).

**Comment by adrianq** [comment]
1. Perfect!
2. I meant between the two sections (doses administered and Q&S Indicators). Sorry for the confusion!

**Comment by tokland** [comment]
Done: 

Screenshot from 2019-04-14 23-32-15

**Comment by adrianq** [comment]
Beautiful! :)

**Pull request merged**
