### PR TITLE
Save dataset custom form

### LINKED ISSUE #48: Add metadata for disaggregation and grey fields

### PR DESCRIPTION
**Pull request by tokland**
### :pushpin: References

* **Issue:** Closes #48 

### :memo: Implementation

- Changed literals for disaggregation step. (#63)
- Save custom form.
- Not done (for another issue): nicer styles for data entry.

### :art: Screenshots

screenshot from 2019-03-08 15-02-59

### CODE REVIEW

**Comment by adrianq** [comment]
@tokland I haven't done a full review of the PR yet but I wanted to generate a new custom form for @matiasgarcia91 to test the dashboards but we are getting an error if we add the three disaggregation levels for vaccine doses administered. See screenshot below. It works however if we only add gender and age range.

screenshot from 2019-03-08 14-38-15

**Comment by tokland** [comment]
It looks like that particular catCombo is missing in dev2, i'll update the
dev2 metadata when i get home. - Mobile

**Comment by adrianq** [comment]
Sure, no worries, this is not blocking anybody so no rush!

**Comment by tokland** [comment]
Ready for review.

- Merged development brach
- Used some styles from NRC.
- Two screenshots one with right-align, the other keeps a different width for each table (this is the currently committed)

Screenshot from 2019-03-10 11-10-44
Screenshot from 2019-03-10 11-11-25

**Pull request merged**
